# Generated by Django 6.0.1 on 2026-02-09 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tracksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksheet',
            name='sender_archived',
            field=models.BooleanField(default=False),
        ),
    ]
