# Generated by Django 6.0.1 on 2026-02-09 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_tracksheet_sender_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracksheet',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='tracksheet',
            name='assigned_task',
        ),
        migrations.RemoveField(
            model_name='tracksheet',
            name='sender_archived',
        ),
        migrations.RemoveField(
            model_name='tracksheet',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tracksheet',
            name='work_done',
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('sender_archived', models.BooleanField(default=False)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('track_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_items', to='dashboard.tracksheet')),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('time', models.TimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('track_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='dashboard.tracksheet')),
            ],
        ),
    ]
