# Generated by Django 6.0.1 on 2026-01-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='esi_percentage',
            field=models.DecimalField(decimal_places=2, default=0.75, help_text='Percentage (e.g., 0.75)', max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed Amount (e.g., 120)', max_digits=10),
        ),
    ]
