# Generated by Django 6.0.1 on 2026-02-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_esi_percentage_user_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='smtp_email',
            field=models.EmailField(blank=True, help_text='Sender Email Address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='App Password', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_server',
            field=models.CharField(default='smtp.gmail.com', max_length=100),
        ),
    ]
